# application.yml 内容
api-module: core/envoy

base:
  api:
    # api前缀
    prefix: /api
  application:
    # 应用名称
    name: isc-envoy-control-service
  server:
    # 是否启用，默认：true
    enable: true
    # 端口号
    port: 32400
    # web框架gin的配置
    gin:
      # 有三种模式：debug/release/test
      mode: debug

  logger:
    # 日志root级别：trace/debug/info/warn/error/fatal/panic，默认：info
    level: info
    # 日志颜色
    color:
      # 启用：true/false，默认：false
      enable: false
    split:
      # 日志是否启用切分：true/false，默认false
      enable: false
      # 日志拆分的单位：MB
      size: 300
    max:
      ## 日志文件最大保留天数
      history: 7
    ## 日志文件目录，默认工程目录的logs文件夹
    dir: ./logs/

  datasource:
    username: isyscore
    password: Isysc0re
    host: 10.30.30.78
    port: 23306
    # 目前支持: mysql、postgresql、sqlite、sqlserver
    driver-name: mysql
    # 数据库名
    db-name: isc_demo
    # 示例：charset=utf8&parseTime=True&loc=Local 等url后面的配置，直接配置即可
    url-config:
      charset: utf8
      parseTime: True
      loc: Local

envoy:
  port: 11000
